services:
  - type: web
    name: netguardgt-api
    env: dotnet
    plan: free
    autoDeploy: true
    buildCommand: dotnet publish NetGuardGT.Api/NetGuardGT.Api.csproj -c Release -o publish
    startCommand: dotnet ./publish/NetGuardGT.Api.dll
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
